# Generated by Django 2.2.16 on 2020-09-22 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=64, null=True)),
                ('dni', models.CharField(blank=True, max_length=32, null=True)),
                ('premium', models.BooleanField(default=False)),
                ('show_occupation', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('show_dni', models.BooleanField(default=True)),
                ('show_birth_day', models.BooleanField(default=True)),
                ('identification_code', models.CharField(max_length=9, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('REQUEST', 'request'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='REQUEST', max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
