# Generated by Django 2.2.16 on 2020-09-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
