# Generated by Django 2.2.16 on 2020-09-19 05:03

import app.utils.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200918_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification_code',
            field=models.CharField(default=app.utils.users.generate_identification_code, max_length=16, unique=True),
        ),
    ]
