# Generated by Django 2.2.16 on 2020-09-21 01:44

import app.utils.users
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200919_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_code',
            field=models.CharField(default=app.utils.users.generate_identification_code, max_length=9, unique=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('REQUEST', 'request'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='REQUEST', max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
