# Generated by Django 2.2.16 on 2020-09-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200920_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
