# Generated by Django 2.2.16 on 2020-09-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200919_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
