# Generated by Django 2.2.16 on 2020-09-21 02:05

import app.utils.events
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(default=app.utils.events.generate_event_code, max_length=9, unique=True),
        ),
    ]
